agentname: master
giturl:
 path: https://github.com/dhivyakiran/portal.git
 branch: development
nexus:
 type: zip
 groupId: portal
 nexusUrl: 10.250.12.199:8081
 nexusVersion: nexus3
 protocol: http
 repository: portal
 test: false
sonar: false
dev_s3bucket:
 sales: dev-salesportal-sales
 agent: dev-salesportal-agent
 members: dev-salesportal-members
