agentname: master
giturl:
 path: https://github.com/dhivyakiran/portal.git
 branch: development
nexus:
 type: zip
 groupId: portal
 nexusUrl: 10.250.12.199:8081
 nexusVersion: nexus3
 protocol: http
 repository: portal
 version: '1.0'
test: false
sonar: true
dev_s3bucket:
 salesurl:
 agenturl:
 membersurl: 
