agentname: master
giturl:
 path: https://github.com/dhivyakiran/portal.git
 branch: development
nexus:
 type: zip
 groupId: portal
 nexusUrl: 10.250.1.153:8081
 nexusVersion: nexus3
 protocol: http
 repository: portal
 version: '1.1'
sonarqube:
 url: 
dev_s3bucket:
 salesurl:
 agenturl:
 membersurl: 
