agentname: master
giturl:
 path: https://github.com/dhivyakiran/portal.git
 branch: development
nexus:
 type: zip
 groupId: portal
 nexusUrl: 10.250.12.199:8081
 nexusVersion: nexus3
 protocol: http
 repository: portal
 test: false
sonar: false
s3bucket:
 dev:
    sales: dev-salesportal-sales
    agent: dev-salesportal-agent
    member: dev-salesportal-members
